workspace(name = "helloworld")

maven_jar(
    name = "servlet_api",
    artifact = "javax.servlet:javax.servlet-api:3.1.0",
)

git_repository(
    name = "io_bazel_rules_appengine",
    remote = "https://github.com/bazelbuild/rules_appengine.git",
    # Check https://github.com/bazelbuild/rules_appengine/releases for the latest version.
    tag = "0.0.5",
)

#Java
load("@io_bazel_rules_appengine//appengine:appengine.bzl", "appengine_repositories")
appengine_repositories()


git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "71bbc36a45346668be52cae4df5a8e7a96920f24",
)

load(
  "@io_bazel_rules_docker//docker:docker.bzl",
  "docker_repositories", "docker_pull"
)
docker_repositories()

docker_pull(
  name = "jetty",
  registry = "gcr.io",
  repository = "distroless/java/jetty",
  digest = "sha256:87ae1deef030f322af909b0fe44edd19b60610a7623dbd5665156757e5930fb3",
)